<?php

return [
    'enabled' => env('PLUGINS_ENABLED', true),

    'path' => env('PLUGINS_PATH', base_path('plugins')),

    'marketplace_url' => env('PLUGIN_MARKETPLACE_URL', 'https://marketplace.xquantoria.com/api/v1'),

    'auto_update' => env('PLUGINS_AUTO_UPDATE', false),

    'max_upload_size' => env('PLUGINS_MAX_UPLOAD_SIZE', 52428800),

    'cache_ttl' => env('PLUGINS_CACHE_TTL', 3600),

    'sandbox' => [
        'enabled' => env('PLUGIN_SANDBOX_ENABLED', true),
        'max_memory' => env('PLUGIN_SANDBOX_MEMORY', '256M'),
        'max_execution_time' => env('PLUGIN_SANDBOX_TIME', 30),
    ],

    'security' => [
        'allowed_functions' => [
            'strlen', 'substr', 'strpos', 'str_replace', 'preg_match', 'preg_replace',
            'array_*', 'count', 'in_array', 'explode', 'implode', 'trim', 'strtolower',
            'strtoupper', 'ucfirst', 'lcfirst', 'ucwords', 'nl2br', 'htmlspecialchars',
            'htmlentities', 'strip_tags', 'json_encode', 'json_decode', 'serialize',
            'unserialize', 'date', 'time', 'strtotime', 'format', 'sprintf', 'printf',
        ],
        'forbidden_functions' => [
            'exec', 'shell_exec', 'system', 'passthru', 'popen', 'proc_open',
            'pcntl_exec', 'eval', 'assert', 'create_function', 'call_user_func',
            'call_user_func_array', 'include', 'include_once', 'require', 'require_once',
            'file_put_contents', 'fwrite', 'fputs', 'fputcsv', 'chmod', 'chown',
            'chgrp', 'unlink', 'rmdir', 'rename', 'copy', 'mkdir', 'move_uploaded_file',
        ],
        'allowed_file_types' => ['zip'],
        'scan_for_malware' => env('PLUGIN_SCAN_MALWARE', true),
    ],

    'hooks' => [
        'actions' => [
            'plugin.activated',
            'plugin.deactivated',
            'plugin.installed',
            'plugin.uninstalled',
            'plugin.updated',
            'post.created',
            'post.updated',
            'post.deleted',
            'post.published',
            'post.scheduled',
            'user.registered',
            'user.login',
            'user.logout',
            'user.updated',
            'user.deleted',
            'comment.created',
            'comment.approved',
            'comment.spam',
            'comment.deleted',
            'media.uploaded',
            'media.deleted',
            'settings.updated',
            'cache.cleared',
            'backup.created',
            'backup.restored',
            'newsletter.subscribed',
            'newsletter.unsubscribed',
            'notification.sent',
        ],
        'filters' => [
            'post.content',
            'post.excerpt',
            'post.title',
            'post.permalink',
            'post.meta',
            'comment.content',
            'user.display_name',
            'media.url',
            'page.title',
            'page.content',
            'email.subject',
            'email.body',
            'api.response',
            'seo.title',
            'seo.description',
            'search.query',
            'search.results',
            'upload.filename',
            'menu.items',
            'breadcrumb.items',
            'widget.output',
            'shortcode.output',
        ],
    ],

    'permissions' => [
        'read_posts',
        'write_posts',
        'delete_posts',
        'read_users',
        'write_users',
        'delete_users',
        'read_settings',
        'write_settings',
        'manage_media',
        'manage_comments',
        'send_emails',
        'access_database',
        'manage_cache',
        'webhook_trigger',
        'api_access',
    ],
];
